name: Build Docker image

on:
  push:
    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag busy-linux
    - name: Copy EFI binary
      run: |
        docker run --detach --name busy-dev -it busy-linux
        docker cp busy-dev:/root/busy-linux.efi ./
        docker stop busy-dev
        ls -l .
    - name: Upload OS as artifact
      uses: actions/upload-artifact@v2
      with:
        name: busy-linux.efi
        path: busy-linux.efi
