name: Build Docker image

on:
  push:
    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build EFI binary
      run: |
        docker build . --file Dockerfile --tag busy-linux:$(date +%s)
        docker run --detach --name busy-dev -it busy-linux
        docker cp busy-dev:/root/busy-linux.efi ./
        docker stop busy-dev
